package com.business.webservice.model;

// Generated 23 Aug, 2015 2:38:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Addresses generated by hbm2java
 */
@Entity
@Table(name = "addresses", catalog = "d2dshopping")
public class Addresses implements java.io.Serializable {

	private Integer addressId;
	private int countryid;
	private int stateid;
	private int cityid;
	private int zipcode;
	private String landmark;
	private String address;
	private int userid;
	private Date createddate;
	private Date lastupdateddate;
	private String createdby;
	private String updatedby;
	private Integer status;

	public Addresses() {
	}

	public Addresses(int countryid, int stateid, int cityid, int zipcode,
			String address, int userid, Date createddate, Date lastupdateddate) {
		this.countryid = countryid;
		this.stateid = stateid;
		this.cityid = cityid;
		this.zipcode = zipcode;
		this.address = address;
		this.userid = userid;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
	}

	public Addresses(int countryid, int stateid, int cityid, int zipcode,
			String landmark, String address, int userid, Date createddate,
			Date lastupdateddate, String createdby, String updatedby,
			Integer status) {
		this.countryid = countryid;
		this.stateid = stateid;
		this.cityid = cityid;
		this.zipcode = zipcode;
		this.landmark = landmark;
		this.address = address;
		this.userid = userid;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AddressID", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "countryid", nullable = false)
	public int getCountryid() {
		return this.countryid;
	}

	public void setCountryid(int countryid) {
		this.countryid = countryid;
	}

	@Column(name = "stateid", nullable = false)
	public int getStateid() {
		return this.stateid;
	}

	public void setStateid(int stateid) {
		this.stateid = stateid;
	}

	@Column(name = "cityid", nullable = false)
	public int getCityid() {
		return this.cityid;
	}

	public void setCityid(int cityid) {
		this.cityid = cityid;
	}

	@Column(name = "zipcode", nullable = false)
	public int getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(int zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "landmark", length = 200)
	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@Column(name = "Address", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", nullable = false, length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", nullable = false, length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby", length = 50)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
