package com.business.webservice.model;

// Generated 23 Aug, 2015 2:38:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "d2dshopping")
public class Admin implements java.io.Serializable {

	private Integer adminid;
	private String adminname;
	private String password;
	private int status;
	private Date createddate;
	private Date lastupdateddate;
	private String description;
	private String createdby;
	private String updatedby;
	private String emailid;
	private String mobileNo;
	private Integer userid;

	public Admin() {
	}

	public Admin(String adminname, String password, int status,
			Date createddate, Date lastupdateddate, String emailid,
			String mobileNo) {
		this.adminname = adminname;
		this.password = password;
		this.status = status;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.emailid = emailid;
		this.mobileNo = mobileNo;
	}

	public Admin(String adminname, String password, int status,
			Date createddate, Date lastupdateddate, String description,
			String createdby, String updatedby, String emailid,
			String mobileNo, Integer userid) {
		this.adminname = adminname;
		this.password = password;
		this.status = status;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.description = description;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.emailid = emailid;
		this.mobileNo = mobileNo;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "adminid", unique = true, nullable = false)
	public Integer getAdminid() {
		return this.adminid;
	}

	public void setAdminid(Integer adminid) {
		this.adminid = adminid;
	}

	@Column(name = "adminname", nullable = false, length = 50)
	public String getAdminname() {
		return this.adminname;
	}

	public void setAdminname(String adminname) {
		this.adminname = adminname;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", nullable = false, length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", nullable = false, length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby", length = 50)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "emailid", nullable = false, length = 50)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "mobileNo", nullable = false, length = 50)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "userid")
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

}
