package com.business.webservice.model;
// default package
// Generated Sep 2, 2016 8:41:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Businesscontact generated by hbm2java
 */
@Entity
@Table(name = "businesscontact", catalog = "business")
public class Businesscontact implements java.io.Serializable {

	private Integer contactid;
	private Integer version;
	private Businesssrc businesssrc;
	private Integer phoneNo;
	private int countryCode;
	private int mobileNo1;
	private Integer mobileNo2;
	private String emailId1;
	private String emailId2;
	private Date createdDate;
	private Date lastUpdateddate;
	private String createdBy;
	private String updatedBy;
	private Integer areaCode;
	private String contactPerson;

	public Businesscontact() {
	}

	public Businesscontact(int countryCode, int mobileNo1, String emailId1,
			Date createdDate, Date lastUpdateddate, String createdBy,
			String updatedBy, String contactPerson) {
		this.countryCode = countryCode;
		this.mobileNo1 = mobileNo1;
		this.emailId1 = emailId1;
		this.createdDate = createdDate;
		this.lastUpdateddate = lastUpdateddate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.contactPerson = contactPerson;
	}

	public Businesscontact(Businesssrc businesssrc, Integer phoneNo,
			int countryCode, int mobileNo1, Integer mobileNo2, String emailId1,
			String emailId2, Date createdDate, Date lastUpdateddate,
			String createdBy, String updatedBy, Integer areaCode,
			String contactPerson) {
		this.businesssrc = businesssrc;
		this.phoneNo = phoneNo;
		this.countryCode = countryCode;
		this.mobileNo1 = mobileNo1;
		this.mobileNo2 = mobileNo2;
		this.emailId1 = emailId1;
		this.emailId2 = emailId2;
		this.createdDate = createdDate;
		this.lastUpdateddate = lastUpdateddate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.areaCode = areaCode;
		this.contactPerson = contactPerson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "contactid", unique = true, nullable = false)
	public Integer getContactid() {
		return this.contactid;
	}

	public void setContactid(Integer contactid) {
		this.contactid = contactid;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BusiSrcID")
	public Businesssrc getBusinesssrc() {
		return this.businesssrc;
	}

	public void setBusinesssrc(Businesssrc businesssrc) {
		this.businesssrc = businesssrc;
	}

	@Column(name = "PhoneNo")
	public Integer getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Integer phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "CountryCode", nullable = false)
	public int getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(int countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "MobileNo1", nullable = false)
	public int getMobileNo1() {
		return this.mobileNo1;
	}

	public void setMobileNo1(int mobileNo1) {
		this.mobileNo1 = mobileNo1;
	}

	@Column(name = "MobileNo2")
	public Integer getMobileNo2() {
		return this.mobileNo2;
	}

	public void setMobileNo2(Integer mobileNo2) {
		this.mobileNo2 = mobileNo2;
	}

	@Column(name = "EmailId1", nullable = false, length = 50)
	public String getEmailId1() {
		return this.emailId1;
	}

	public void setEmailId1(String emailId1) {
		this.emailId1 = emailId1;
	}

	@Column(name = "EmailId2", length = 50)
	public String getEmailId2() {
		return this.emailId2;
	}

	public void setEmailId2(String emailId2) {
		this.emailId2 = emailId2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdateddate", nullable = false, length = 19)
	public Date getLastUpdateddate() {
		return this.lastUpdateddate;
	}

	public void setLastUpdateddate(Date lastUpdateddate) {
		this.lastUpdateddate = lastUpdateddate;
	}

	@Column(name = "CreatedBy", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "UpdatedBy", nullable = false, length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "AreaCode")
	public Integer getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(Integer areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "ContactPerson", nullable = false, length = 50)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

}
