package com.business.webservice.model;
// default package
// Generated Sep 2, 2016 8:41:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Businesssrc generated by hbm2java
 */
@Entity
@Table(name = "businesssrc", catalog = "business")
public class Businesssrc implements java.io.Serializable {

	private Integer busiSrcId;
	private Integer version;
	private Applogincredentials applogincredentials;
	private User user;
	private Integer busiTypeid;
	private String busiName;
	private Date createddate;
	private Date lastupdateddate;
	private String createdby;
	private String updatedby;
	private Integer acstatus;
	private String pancardNo;
	private String adharCardNo;
	private Set<Businesscontact> businesscontacts = new HashSet<Businesscontact>(
			0);

	public Businesssrc() {
	}

	public Businesssrc(Date createddate, Date lastupdateddate) {
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
	}

	public Businesssrc(Applogincredentials applogincredentials, User user,
			Integer busiTypeid, String busiName, Date createddate,
			Date lastupdateddate, String createdby, String updatedby,
			Integer acstatus, String pancardNo, String adharCardNo,
			Set<Businesscontact> businesscontacts) {
		this.applogincredentials = applogincredentials;
		this.user = user;
		this.busiTypeid = busiTypeid;
		this.busiName = busiName;
		this.createddate = createddate;
		this.lastupdateddate = lastupdateddate;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.acstatus = acstatus;
		this.pancardNo = pancardNo;
		this.adharCardNo = adharCardNo;
		this.businesscontacts = businesscontacts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BusiSrcID", unique = true, nullable = false)
	public Integer getBusiSrcId() {
		return this.busiSrcId;
	}

	public void setBusiSrcId(Integer busiSrcId) {
		this.busiSrcId = busiSrcId;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "appid")
	public Applogincredentials getApplogincredentials() {
		return this.applogincredentials;
	}

	public void setApplogincredentials(Applogincredentials applogincredentials) {
		this.applogincredentials = applogincredentials;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "busiTypeid")
	public Integer getBusiTypeid() {
		return this.busiTypeid;
	}

	public void setBusiTypeid(Integer busiTypeid) {
		this.busiTypeid = busiTypeid;
	}

	@Column(name = "BusiName", length = 200)
	public String getBusiName() {
		return this.busiName;
	}

	public void setBusiName(String busiName) {
		this.busiName = busiName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddate", nullable = false, length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdateddate", nullable = false, length = 19)
	public Date getLastupdateddate() {
		return this.lastupdateddate;
	}

	public void setLastupdateddate(Date lastupdateddate) {
		this.lastupdateddate = lastupdateddate;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby", length = 50)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "ACstatus")
	public Integer getAcstatus() {
		return this.acstatus;
	}

	public void setAcstatus(Integer acstatus) {
		this.acstatus = acstatus;
	}

	@Column(name = "PancardNo", length = 50)
	public String getPancardNo() {
		return this.pancardNo;
	}

	public void setPancardNo(String pancardNo) {
		this.pancardNo = pancardNo;
	}

	@Column(name = "AdharCardNo", length = 50)
	public String getAdharCardNo() {
		return this.adharCardNo;
	}

	public void setAdharCardNo(String adharCardNo) {
		this.adharCardNo = adharCardNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businesssrc")
	public Set<Businesscontact> getBusinesscontacts() {
		return this.businesscontacts;
	}

	public void setBusinesscontacts(Set<Businesscontact> businesscontacts) {
		this.businesscontacts = businesscontacts;
	}

}
