package com.business.webservice.model;

// Generated 23 Aug, 2015 2:38:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReviewsId generated by hbm2java
 */
@Embeddable
public class ReviewsId implements java.io.Serializable {

	private Integer reviewid;
	private String review;
	private Integer userid;
	private Integer productid;
	private Integer reviewpoints;
	private Date createddate;
	private Date updateddate;
	private String createdby;
	private String updatedby;

	public ReviewsId() {
	}

	public ReviewsId(Integer reviewid, String review, Integer userid,
			Integer productid, Integer reviewpoints, Date createddate,
			Date updateddate, String createdby, String updatedby) {
		this.reviewid = reviewid;
		this.review = review;
		this.userid = userid;
		this.productid = productid;
		this.reviewpoints = reviewpoints;
		this.createddate = createddate;
		this.updateddate = updateddate;
		this.createdby = createdby;
		this.updatedby = updatedby;
	}

	@Column(name = "reviewid")
	public Integer getReviewid() {
		return this.reviewid;
	}

	public void setReviewid(Integer reviewid) {
		this.reviewid = reviewid;
	}

	@Column(name = "review", length = 65535)
	public String getReview() {
		return this.review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	@Column(name = "userid")
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@Column(name = "productid")
	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	@Column(name = "reviewpoints")
	public Integer getReviewpoints() {
		return this.reviewpoints;
	}

	public void setReviewpoints(Integer reviewpoints) {
		this.reviewpoints = reviewpoints;
	}

	@Column(name = "createddate", length = 19)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "updateddate", length = 19)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@Column(name = "createdby", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby", length = 50)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReviewsId))
			return false;
		ReviewsId castOther = (ReviewsId) other;

		return ((this.getReviewid() == castOther.getReviewid()) || (this
				.getReviewid() != null && castOther.getReviewid() != null && this
				.getReviewid().equals(castOther.getReviewid())))
				&& ((this.getReview() == castOther.getReview()) || (this
						.getReview() != null && castOther.getReview() != null && this
						.getReview().equals(castOther.getReview())))
				&& ((this.getUserid() == castOther.getUserid()) || (this
						.getUserid() != null && castOther.getUserid() != null && this
						.getUserid().equals(castOther.getUserid())))
				&& ((this.getProductid() == castOther.getProductid()) || (this
						.getProductid() != null
						&& castOther.getProductid() != null && this
						.getProductid().equals(castOther.getProductid())))
				&& ((this.getReviewpoints() == castOther.getReviewpoints()) || (this
						.getReviewpoints() != null
						&& castOther.getReviewpoints() != null && this
						.getReviewpoints().equals(castOther.getReviewpoints())))
				&& ((this.getCreateddate() == castOther.getCreateddate()) || (this
						.getCreateddate() != null
						&& castOther.getCreateddate() != null && this
						.getCreateddate().equals(castOther.getCreateddate())))
				&& ((this.getUpdateddate() == castOther.getUpdateddate()) || (this
						.getUpdateddate() != null
						&& castOther.getUpdateddate() != null && this
						.getUpdateddate().equals(castOther.getUpdateddate())))
				&& ((this.getCreatedby() == castOther.getCreatedby()) || (this
						.getCreatedby() != null
						&& castOther.getCreatedby() != null && this
						.getCreatedby().equals(castOther.getCreatedby())))
				&& ((this.getUpdatedby() == castOther.getUpdatedby()) || (this
						.getUpdatedby() != null
						&& castOther.getUpdatedby() != null && this
						.getUpdatedby().equals(castOther.getUpdatedby())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getReviewid() == null ? 0 : this.getReviewid().hashCode());
		result = 37 * result
				+ (getReview() == null ? 0 : this.getReview().hashCode());
		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result
				+ (getProductid() == null ? 0 : this.getProductid().hashCode());
		result = 37
				* result
				+ (getReviewpoints() == null ? 0 : this.getReviewpoints()
						.hashCode());
		result = 37
				* result
				+ (getCreateddate() == null ? 0 : this.getCreateddate()
						.hashCode());
		result = 37
				* result
				+ (getUpdateddate() == null ? 0 : this.getUpdateddate()
						.hashCode());
		result = 37 * result
				+ (getCreatedby() == null ? 0 : this.getCreatedby().hashCode());
		result = 37 * result
				+ (getUpdatedby() == null ? 0 : this.getUpdatedby().hashCode());
		return result;
	}

}
