package com.business.webservice.model;

// Generated 23 Aug, 2015 2:38:46 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Reviews generated by hbm2java
 */
@Entity
@Table(name = "reviews", catalog = "d2dshopping")
public class Reviews implements java.io.Serializable {

	private ReviewsId id;

	public Reviews() {
	}

	public Reviews(ReviewsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "reviewid", column = @Column(name = "reviewid")),
			@AttributeOverride(name = "review", column = @Column(name = "review", length = 65535)),
			@AttributeOverride(name = "userid", column = @Column(name = "userid")),
			@AttributeOverride(name = "productid", column = @Column(name = "productid")),
			@AttributeOverride(name = "reviewpoints", column = @Column(name = "reviewpoints")),
			@AttributeOverride(name = "createddate", column = @Column(name = "createddate", length = 19)),
			@AttributeOverride(name = "updateddate", column = @Column(name = "updateddate", length = 19)),
			@AttributeOverride(name = "createdby", column = @Column(name = "createdby", length = 50)),
			@AttributeOverride(name = "updatedby", column = @Column(name = "updatedby", length = 50)) })
	public ReviewsId getId() {
		return this.id;
	}

	public void setId(ReviewsId id) {
		this.id = id;
	}

}
