package com.business.webservice.model;

// Generated 23 Aug, 2015 2:38:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Specification generated by hbm2java
 */
@Entity
@Table(name = "specification", catalog = "d2dshopping")
public class Specification implements java.io.Serializable {

	private int specificationid;
	private String warranty;
	private Integer productid;
	
	@Embedded
	private AuditInfo auditInfo;

	public Specification() {
	}

	public Specification(int specificationid) {
		this.specificationid = specificationid;
	}

	public Specification(int specificationid, String warranty,
			 Integer productid) {
		this.specificationid = specificationid;
		this.warranty = warranty;
		this.productid = productid;
	}

	@Id
	@Column(name = "specificationid", unique = true, nullable = false)
	public int getSpecificationid() {
		return this.specificationid;
	}

	public void setSpecificationid(int specificationid) {
		this.specificationid = specificationid;
	}

	@Column(name = "warranty", length = 100)
	public String getWarranty() {
		return this.warranty;
	}

	public void setWarranty(String warranty) {
		this.warranty = warranty;
	}
	@Column(name = "productid")
	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	public AuditInfo getAuditInfo() {
		return auditInfo;
	}

	public void setAuditInfo(AuditInfo auditInfo) {
		this.auditInfo = auditInfo;
	}
}
